### ISSUE TITLE
Не работает русский вариант входа в Осадную башню, диалог с Лазло

### ISSUE THREAD

**Issue by gonkong** [EugVV/PSTEE-russian#1]
Привет,

столкнулся с такой загвоздкой, имеется версия 3.1.3 и перевод с яндекс диска.

Доходим до разговора с LAZLO (Лазло), насчет входа в (Siege Tower) Осадную Башню, квест из Кузни, получить клетку.  

Диалог не дает продвижения. Наша задача войти в башню, но способ знает только Лазло.  Переходим в англ язык, и все находится. По мере разговора идет обновление дневника.  Переходим опять в русский язык, и читаем то, чего не могли добиться ранее, в т.ч. дневник.

**Comment by EugVV** [comment]
Я этот квест с переводом проходил, естественно, никаких проблем не было. Конкретнее, в каком месте диалог не даёт продвижения? Сэйв также не помешает.

Посмотрел, этот диалог выглядит абсолютно нормально. Просишь парня рассказать о районе, потом спрашиваешь, почему район так называется, и дальше, каждый раз можно первую реплику - всё дерево без проблем проходится. Добавление информации в дневник не могу проверить (нет сэйва перед этим диалогом, всё уже в дневнике), но и с этим проблем быть не должно.

**Comment by EugVV** [comment]
Больше двух недель прошло, и ни сэйвов, ни дополнительной информации. Закрывать тему?

**Comment by gonkong** [comment]
Обновился из хранилища, и проблема исчезла. Вероятно она была решена ранее.

**Comment by EugVV** [comment]
Ну ладно тогда. Закрываю.
