### ISSUE TITLE
Ошибки в описании нескольких предметов

### ISSUE THREAD

**Issue by Al-Snide** [EugVV/PSTEE-russian#2]
У предметов "Чара сердца", "Чара крови" и "Чара сгустка крови" в описании написано местоимение "Этот", а не "Эта".

**Comment by EugVV** [comment]
[Исправлено](https://github.com/EugVV/PSTEE-russian/commit/4ecd54ed6ce904a1a3303389a6302b4be44fa25c), спасибо.
